import { StyleSheet } from "react-native";

export const modalStyles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)", // Dark overlay
  },
  modalContainer: {
    width: "90%",
    backgroundColor: "#373737",
    padding: 20,
    borderRadius: 10,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 15,
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    padding: 15,
    borderColor: "#B3B3B3",
    borderRadius: 10,
    color: "#B3B3B3",
  },
  smallInput: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "48%",
    borderWidth: 1,
    padding: 5,
    borderColor: "#B3B3B3",
    borderRadius: 10,
    color: "#B3B3B3",
  },
  buttonsRow: {
    width: "100%",
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: 10,
  },
  selectableButton: {
    backgroundColor: "#2A2A2A",
    paddingVertical: 17,
    paddingHorizontal: 15,
    borderWidth: 2,
    borderColor: "#3C3C3CCC",
    borderRadius: 10,
    color: "#7C7C7C",
  },
  searchButtonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  closeButton: {
    width: "100%",
    padding: 15,
    backgroundColor: "#6B6562",
    borderRadius: 10,
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
});
